### PR TITLE
add size arg to upsampling

### PR DESCRIPTION
**Pull request by rlee3359**
This just implements the 'size' argument for R2Usampling, following [torch's Upsampling](https://pytorch.org/docs/stable/_modules/torch/nn/modules/upsampling.html#UpsamplingBilinear2d) Placed after 'scale_factor' as to not break existing code that uses only scale without specifying keyword.

Mentioned here in #4

### CODE REVIEW

**Comment by Gabri95** [comment]
Hi @rlee3359 

Thanks for opening this pull request!

Unfortunately, I can not accept it right now since I first need to set up the [DCO app](https://github.com/apps/dco).
Once that is done (hopefully in a couple of days), I will ask you to sign-off your commit to agree with the library's license.

Thanks again for opening our first pull request! :tada: 

Gabriele

**Comment by Gabri95** [comment]
Ok, I think the DCO app is set up now.

I need you to add a 'Signed-off-by' line in your commit to agree with the current license (see [dco](https://github.com/probot/dco)).
Only then I can accept your pull request.

Thanks again for your contribution!

Best,
Gabriele

**Comment by rlee3359** [comment]
Sorry for the late response! I've amended the commit with the sign-off, so it should all be good now! Let me know if there's any issues.

Thanks!

**Comment by Gabri95** [comment]
Hi @rlee3359 

I have finally merged the pull request, thanks a lot for your contribution!

Note that I have added some small changes,  you can check them [here](https://quva-lab.github.io/escnn/api/escnn.nn.html#upsampling).

Best,
Gabriele

**Comment by rlee3359** [comment]
Awesome, thanks!

**Pull request merged**
