### PR TITLE
fix numpy version for deprecation of np.float, np.int, np.bool etc

### LINKED ISSUE #25: Use of `np.float` and `np.int` etc
Thanks @Gabri95 et al for providing this library. I am currently ramping up my use of it. I however discovered a small bug, that makes `escnn` unusable with any `numpy` version higher or equal to `1.24`.

The numpy team deprecated the `np.float` and `np.int` and `np.bool` aliases to the respective python internals.
https://numpy.org/doc/stable/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated
From numpy `1.24` and higher, their use produces an error which makes the example given in the README.md break immediately.

### PR DESCRIPTION
**Pull request by psteinb**
Fixes #25

### CODE REVIEW

**Comment by Gabri95** [comment]
hi @psteinb 

Thanks a lot for spotting this error and for preparing this pull request!

Could you sign-off you commits (see the DCO message above) so I can merge it?

Thanks,
Gabriele

**Comment by psteinb** [comment]
Done. This DCO requirement is new to me.
As an idea: It might be worthwhile to document this in a `CONTRIBUTING.md` file located at the root of the repo.

**Comment by Gabri95** [comment]
Hi @psteinb 

You are right, I will add a few comments in a CONTRIBUTING.md file.

Regarding the pull request, I see you changed the requirement to `numpy<1.24`. 
Rather than constraining the maximum version of numpy, I'd rather replace all `np.int` etc.. with `int`.
I understand this should work for all recent versions of numpy.


Would this solution work well for you?

Thanks,
Gabriele

**Comment by psteinb** [comment]
No doubt, my PR is a monkey patch. The intention behind it was, to get going
quickly. Indeed, if the root cause is removed from the `escnn` code (i.e. all
occurrences of `np.float`, `np.int`, `np.bool` etc), the limit to the numpy
version needs to be adapted (again) too.

I currently lack the time to fix all of these uses of `np.float` etc and put
these changes this in a PR, but I wanted to help and provide the monkey patch.

**Pull request merged**
